// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type StorageIoKey struct {
	_        structs.HostLayout
	DevMajor uint32
	DevMinor uint32
	Sector   uint64
}

type StorageIoValue struct {
	_        structs.HostLayout
	IssueNs  uint64
	CgroupId uint64
	Bytes    uint32
	Opcode   uint8
	Padding  [3]uint8
}

// LoadStorage returns the embedded CollectionSpec for Storage.
func LoadStorage() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_StorageBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Storage: %w", err)
	}

	return spec, err
}

// LoadStorageObjects loads Storage and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*StorageObjects
//	*StoragePrograms
//	*StorageMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadStorageObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadStorage()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// StorageSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type StorageSpecs struct {
	StorageProgramSpecs
	StorageMapSpecs
	StorageVariableSpecs
}

// StorageProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type StorageProgramSpecs struct {
	TraceBlockRqComplete *ebpf.ProgramSpec `ebpf:"trace_block_rq_complete"`
	TraceBlockRqIssue    *ebpf.ProgramSpec `ebpf:"trace_block_rq_issue"`
}

// StorageMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type StorageMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	InflightIo *ebpf.MapSpec `ebpf:"inflight_io"`
}

// StorageVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type StorageVariableSpecs struct {
}

// StorageObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadStorageObjects or ebpf.CollectionSpec.LoadAndAssign.
type StorageObjects struct {
	StoragePrograms
	StorageMaps
	StorageVariables
}

func (o *StorageObjects) Close() error {
	return _StorageClose(
		&o.StoragePrograms,
		&o.StorageMaps,
	)
}

// StorageMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadStorageObjects or ebpf.CollectionSpec.LoadAndAssign.
type StorageMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	InflightIo *ebpf.Map `ebpf:"inflight_io"`
}

func (m *StorageMaps) Close() error {
	return _StorageClose(
		m.Events,
		m.InflightIo,
	)
}

// StorageVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadStorageObjects or ebpf.CollectionSpec.LoadAndAssign.
type StorageVariables struct {
}

// StoragePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadStorageObjects or ebpf.CollectionSpec.LoadAndAssign.
type StoragePrograms struct {
	TraceBlockRqComplete *ebpf.Program `ebpf:"trace_block_rq_complete"`
	TraceBlockRqIssue    *ebpf.Program `ebpf:"trace_block_rq_issue"`
}

func (p *StoragePrograms) Close() error {
	return _StorageClose(
		p.TraceBlockRqComplete,
		p.TraceBlockRqIssue,
	)
}

func _StorageClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed storage_x86_bpfel.o
var _StorageBytes []byte
