//go:build !ignore_autogenerated

/*
Copyright 2025 Tapio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonSetStatus) DeepCopyInto(out *DaemonSetStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonSetStatus.
func (in *DaemonSetStatus) DeepCopy() *DaemonSetStatus {
	if in == nil {
		return nil
	}
	out := new(DaemonSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkObserverConfig) DeepCopyInto(out *NetworkObserverConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkObserverConfig.
func (in *NetworkObserverConfig) DeepCopy() *NetworkObserverConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkObserverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerObserverConfig) DeepCopyInto(out *SchedulerObserverConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerObserverConfig.
func (in *SchedulerObserverConfig) DeepCopy() *SchedulerObserverConfig {
	if in == nil {
		return nil
	}
	out := new(SchedulerObserverConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TapioObserver) DeepCopyInto(out *TapioObserver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TapioObserver.
func (in *TapioObserver) DeepCopy() *TapioObserver {
	if in == nil {
		return nil
	}
	out := new(TapioObserver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TapioObserver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TapioObserverList) DeepCopyInto(out *TapioObserverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TapioObserver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TapioObserverList.
func (in *TapioObserverList) DeepCopy() *TapioObserverList {
	if in == nil {
		return nil
	}
	out := new(TapioObserverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TapioObserverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TapioObserverSpec) DeepCopyInto(out *TapioObserverSpec) {
	*out = *in
	if in.NetworkObserver != nil {
		in, out := &in.NetworkObserver, &out.NetworkObserver
		*out = new(NetworkObserverConfig)
		**out = **in
	}
	if in.SchedulerObserver != nil {
		in, out := &in.SchedulerObserver, &out.SchedulerObserver
		*out = new(SchedulerObserverConfig)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TapioObserverSpec.
func (in *TapioObserverSpec) DeepCopy() *TapioObserverSpec {
	if in == nil {
		return nil
	}
	out := new(TapioObserverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TapioObserverStatus) DeepCopyInto(out *TapioObserverStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DaemonSetStatus != nil {
		in, out := &in.DaemonSetStatus, &out.DaemonSetStatus
		*out = new(DaemonSetStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TapioObserverStatus.
func (in *TapioObserverStatus) DeepCopy() *TapioObserverStatus {
	if in == nil {
		return nil
	}
	out := new(TapioObserverStatus)
	in.DeepCopyInto(out)
	return out
}
