// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadNodePMC returns the embedded CollectionSpec for NodePMC.
func LoadNodePMC() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NodePMCBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NodePMC: %w", err)
	}

	return spec, err
}

// LoadNodePMCObjects loads NodePMC and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NodePMCObjects
//	*NodePMCPrograms
//	*NodePMCMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNodePMCObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNodePMC()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NodePMCSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NodePMCSpecs struct {
	NodePMCProgramSpecs
	NodePMCMapSpecs
	NodePMCVariableSpecs
}

// NodePMCProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NodePMCProgramSpecs struct {
	SamplePmc *ebpf.ProgramSpec `ebpf:"sample_pmc"`
}

// NodePMCMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NodePMCMapSpecs struct {
	Events          *ebpf.MapSpec `ebpf:"events"`
	PmcCycles       *ebpf.MapSpec `ebpf:"pmc_cycles"`
	PmcInstructions *ebpf.MapSpec `ebpf:"pmc_instructions"`
	PmcStalls       *ebpf.MapSpec `ebpf:"pmc_stalls"`
}

// NodePMCVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NodePMCVariableSpecs struct {
}

// NodePMCObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNodePMCObjects or ebpf.CollectionSpec.LoadAndAssign.
type NodePMCObjects struct {
	NodePMCPrograms
	NodePMCMaps
	NodePMCVariables
}

func (o *NodePMCObjects) Close() error {
	return _NodePMCClose(
		&o.NodePMCPrograms,
		&o.NodePMCMaps,
	)
}

// NodePMCMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNodePMCObjects or ebpf.CollectionSpec.LoadAndAssign.
type NodePMCMaps struct {
	Events          *ebpf.Map `ebpf:"events"`
	PmcCycles       *ebpf.Map `ebpf:"pmc_cycles"`
	PmcInstructions *ebpf.Map `ebpf:"pmc_instructions"`
	PmcStalls       *ebpf.Map `ebpf:"pmc_stalls"`
}

func (m *NodePMCMaps) Close() error {
	return _NodePMCClose(
		m.Events,
		m.PmcCycles,
		m.PmcInstructions,
		m.PmcStalls,
	)
}

// NodePMCVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNodePMCObjects or ebpf.CollectionSpec.LoadAndAssign.
type NodePMCVariables struct {
}

// NodePMCPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNodePMCObjects or ebpf.CollectionSpec.LoadAndAssign.
type NodePMCPrograms struct {
	SamplePmc *ebpf.Program `ebpf:"sample_pmc"`
}

func (p *NodePMCPrograms) Close() error {
	return _NodePMCClose(
		p.SamplePmc,
	)
}

func _NodePMCClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed nodepmc_x86_bpfel.o
var _NodePMCBytes []byte
