// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NetworkConnKey struct {
	_     structs.HostLayout
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

type NetworkRetransmitStats struct {
	_                structs.HostLayout
	TotalPackets     uint64
	Retransmits      uint64
	LastRetransmitNs uint64
	RstReceived      uint8
	Padding          [7]uint8
}

type NetworkRttBaseline struct {
	_              structs.HostLayout
	BaselineUs     uint32
	SampleCount    uint8
	State          uint8
	_              [2]byte
	LastUpdateNs   uint64
	LastActivityNs uint64
}

// LoadNetwork returns the embedded CollectionSpec for Network.
func LoadNetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Network: %w", err)
	}

	return spec, err
}

// LoadNetworkObjects loads Network and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetworkObjects
//	*NetworkPrograms
//	*NetworkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetworkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetworkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkSpecs struct {
	NetworkProgramSpecs
	NetworkMapSpecs
	NetworkVariableSpecs
}

// NetworkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkProgramSpecs struct {
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
	TraceTcpReceiveReset  *ebpf.ProgramSpec `ebpf:"trace_tcp_receive_reset"`
	TraceTcpRetransmitSkb *ebpf.ProgramSpec `ebpf:"trace_tcp_retransmit_skb"`
}

// NetworkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkMapSpecs struct {
	BaselineRtt  *ebpf.MapSpec `ebpf:"baseline_rtt"`
	ConnStats    *ebpf.MapSpec `ebpf:"conn_stats"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	TapioMetrics *ebpf.MapSpec `ebpf:"tapio_metrics"`
}

// NetworkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetworkVariableSpecs struct {
}

// NetworkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkObjects struct {
	NetworkPrograms
	NetworkMaps
	NetworkVariables
}

func (o *NetworkObjects) Close() error {
	return _NetworkClose(
		&o.NetworkPrograms,
		&o.NetworkMaps,
	)
}

// NetworkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkMaps struct {
	BaselineRtt  *ebpf.Map `ebpf:"baseline_rtt"`
	ConnStats    *ebpf.Map `ebpf:"conn_stats"`
	Events       *ebpf.Map `ebpf:"events"`
	TapioMetrics *ebpf.Map `ebpf:"tapio_metrics"`
}

func (m *NetworkMaps) Close() error {
	return _NetworkClose(
		m.BaselineRtt,
		m.ConnStats,
		m.Events,
		m.TapioMetrics,
	)
}

// NetworkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkVariables struct {
}

// NetworkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetworkPrograms struct {
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
	TraceTcpReceiveReset  *ebpf.Program `ebpf:"trace_tcp_receive_reset"`
	TraceTcpRetransmitSkb *ebpf.Program `ebpf:"trace_tcp_retransmit_skb"`
}

func (p *NetworkPrograms) Close() error {
	return _NetworkClose(
		p.TraceInetSockSetState,
		p.TraceTcpReceiveReset,
		p.TraceTcpRetransmitSkb,
	)
}

func _NetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed network_arm64_bpfel.o
var _NetworkBytes []byte
